sudo: required
services:
 - docker

before_install:
 - sudo pip install tox

# setup databases
before_script:
 - cp conf/development.env.example conf/development.env
 - docker-compose build

script:
 - tox
 - docker-compose -f docker-compose-test.yml run --rm test bash bin/test_with_coverage -v2
 - docker-compose run --rm -e CABOT_SUPERUSER_USERNAME='admin' -e CABOT_SUPERUSER_PASSWORD='pass' web true

after_success:
  - pip install codecov
  - pip install django_coverage_plugin==1.4.2
  - codecov
